name: Build
 
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version: v(?)'
        required: true
        type: string
 
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Delete
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
 
  build:
    permissions: write-all
    needs: [clean]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { build: core, goos: android, goarch: arm, cc: armv7a-linux-androideabi23, cgo: 1 }
          - { build: core, goos: android, goarch: arm64, cc: aarch64-linux-android23, cgo: 0 }
          - { build: sfa, platform: armeabi-v7a, cc: armv7a-linux-androideabi23 }
          - { build: sfa, platform: arm64-v8a, cc: aarch64-linux-android23 }
 
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
 
      - name: Set up go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          check-latest: true
          cache: true
 
      - name: Set up ndk
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28
          add-to-path: true
 
      - name: Set up version
        id: version
        run: |
          version="${{ inputs.version }}"
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "VERSION=${version}" >> $GITHUB_ENV
          echo "TIME=$(TZ=Asia/Shanghai date)" >> $GITHUB_ENV
 
      - name: Build core bin
        if: matrix.build == 'core'
        env:
          TAGS: "with_gvisor,with_quic,with_utls,with_clash_api"
          NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          CC=${NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/${{ matrix.cc }}-clang \
          CXX="${CC}++" \
          CGO_ENABLED=${{ matrix.cgo }} \
          GOOS=${{ matrix.goos }} \
          GOARCH=${{ matrix.goarch }} \
          CC=$CC CXX=$CXX go build -trimpath -ldflags '-X github.com/sagernet/sing-box/constant.Version=${VERSION} -s -w -buildid= -X internal/godebug.defaultGODEBUG=multipathtcp=0 -checklinkname=0' -tags ${TAGS} ./cmd/sing-box
 
      - name: Compress with upx
        if: matrix.build == 'core'
        run: |
          upx="$(curl --retry 5 --retry-all-errors -sL "https://github.com/upx/upx/releases$(curl --retry 5 --retry-all-errors -sL "https://github.com/upx/upx/releases$(curl --retry 5 --retry-all-errors -sL "https://github.com/upx/upx/releases/latest" | grep -Eo '/expanded_assets/[^\"]+')" | grep -Eo '/download/[^"]+amd64_linux[^"]+')" |tar xvJf - |grep '/upx$')"
          $upx --best ./sing-box
 
      - name: Upload core bin
        if: matrix.build == 'core'
        uses: actions/upload-artifact@v4
        with:
          name: sing-box-${{ env.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: sing-box
          compression-level: 9
 
      - name: Checkout sfa
        if: matrix.build == 'sfa'
        uses: actions/checkout@v5
        with:
          repository: SagerNet/sing-box-for-android
          ref: dev
          path: sfa
          submodules: recursive
 
      - name: Set up java
        if: matrix.build == 'sfa'
        uses: actions/setup-java@v5
        with:
          distribution: 'oracle'
          java-version: 17
          check-latest: true
 
      - name: Set up sdk
        if: matrix.build == 'sfa'
        id: sdk
        run: echo "version=$(ls $ANDROID_HOME/build-tools | tail -n 1)" >> $GITHUB_OUTPUT
 
      - name: Gradle cache
        uses: actions/cache@v5
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle') }}
 
      - name: Build sfa lib
        if: matrix.build == 'sfa'
        env:
          TAGS: "with_gvisor,with_quic,with_utls,with_clash_api"
          NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          mkdir -p sfa/app/libs/
          make lib_install
          CC=${NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/${{ matrix.cc }}-clang \
          CXX="${CC}++" \
          CC=$CC CXX=$CXX CGO_ENABLED=1 gomobile bind -target=android/arm,android/arm64 -trimpath -androidapi 21 -javapkg=io.nekohasekai -libname=box -tags ${TAGS} -ldflags "-X github.com/sagernet/sing-box/constant.Version=${VERSION} -s -w -buildid= -X internal/godebug.defaultGODEBUG=multipathtcp=0 -checklinkname=0" ./experimental/libbox
          cp ./libbox.aar sfa/app/libs/
 
      - name: Build sfa
        if: matrix.build == 'sfa'
        run: |
          cd sfa
          sed -i '/signingConfigs\.getByName/d' app/build.gradle.kts
          chmod +x ./gradlew
          ./gradlew :app:clean :app:assembleOtherRelease && ./gradlew --stop
 
      - name: Sign sfa
        if: matrix.build == 'sfa'
        uses: doncax/android-sign@main
        env:
          BUILD_TOOLS_VERSION: ${{steps.sdk.outputs.version}}
        with:
          releaseDirectory: sfa/app/build/outputs/apk/other/release
          signingKeyBase64: ${{ secrets.SIGN_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
 
      - name: Upload sfa artifacts
        if: matrix.build == 'sfa'
        uses: actions/upload-artifact@v4
        with:
          name: sfa-${{ env.VERSION }}-${{ matrix.platform }}
          path: sfa/app/build/outputs/apk/other/release/*-${{ matrix.platform }}-signed.apk
          compression-level: 9
