name: Build

on:
  workflow_dispatch:
  push:

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
    - name: Delete
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0

  core:
    permissions:
      contents: write
    needs: [clean]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jobs:
          - { goos: android, goarch: arm, ndk: armv7a-linux-androideabi21, output: arm }
          - { goos: android, goarch: arm64, ndk: aarch64-linux-android21, output: arm64 }
          - { goos: linux, goarch: arm, output: arm }
          - { goos: linux, goarch: arm64, output: arm64 }
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        repository: XTLS/Xray-core
        path: xray
        fetch-depth: 0

    - name: Set up go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.24
        check-latest: true

    - name: Set up ndk
      if: matrix.jobs.goos == 'android'
      run: |
          wget -qO android-ndk.zip https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
          unzip android-ndk.zip
          rm android-ndk.zip
        
    - name: Build core
      run: |
        cd xray
        COMMID=$(git rev-parse --short HEAD)

        if [ "${{ matrix.jobs.goos }}" = "android" ]; then
          export CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/${{ matrix.jobs.ndk }}-clang

          GOARCH=${{ matrix.jobs.goarch }} GOOS=android CGO_ENABLED=1 \
          go build -o xray \
            -trimpath \
            -buildvcs=false \
            -ldflags="-X github.com/xtls/xray-core/core.build=$COMMID -s -w -buildid=" ./main
        else
          GOARCH=${{ matrix.jobs.goarch }} GOOS=linux \
          go build -o xray \
            -trimpath \
            -buildvcs=false \
            -ldflags="-X github.com/xtls/xray-core/core.build=$COMMID -s -w -buildid=" ./main
        fi

    - name: Compress upx
      run: |
        cd xray
        upx --best xray

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: xray-${{ matrix.jobs.goos }}-${{ matrix.jobs.goarch }}
        path: ./xray/xray